# Generated by Django 4.2.7 on 2023-12-17 14:18

import django.core.validators
from django.db import migrations, models
import users.models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(default='', max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name="ім'я"),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='last_name',
            field=models.CharField(default='', max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='прізвище'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/profile_picture_default.jpg', upload_to=users.models.user_directory_path, validators=[users.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='telephone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='користувач'),
        ),
    ]
