# Generated by Django 4.2.7 on 2023-12-19 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_siteuser_email_alter_siteuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='тема листа')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('content', models.TextField(verbose_name='зміст листа')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='дата відправки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса відправнка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'зворотній звязок',
                'verbose_name_plural': 'зворотній звязок',
                'db_table': 'app_feedback',
                'ordering': ['-time_create'],
            },
        ),
    ]
