# Generated by Django 4.2.7 on 2023-12-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='product')),
                ('price', models.FloatField(default=0, verbose_name='price')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'product',
                'ordering': ['product', 'price'],
            },
        ),
    ]
